import React from "react";
import { motion } from "motion/react";

interface StaticPageProps {
  title: string;
  children: React.ReactNode;
}

const StaticPageLayout = ({ title, children }: StaticPageProps) => (
  <div className="min-h-screen pt-24 pb-12 bg-black text-zinc-300">
    <div className="max-w-3xl mx-auto px-4">
      <motion.h1 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-4xl font-bold text-white mb-8 tracking-tight"
      >
        {title}
      </motion.h1>
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.2 }}
        className="prose prose-invert prose-emerald max-w-none"
      >
        {children}
      </motion.div>
    </div>
  </div>
);

export const PrivacyPolicy = () => (
  <StaticPageLayout title="Privacy Policy">
    <p>Last Updated: February 21, 2026</p>
    <p>At Abilities AI, we take your privacy seriously. This policy explains how we collect, use, and protect your personal information.</p>
    
    <h2 className="text-xl font-bold text-white mt-8 mb-4">1. Information We Collect</h2>
    <p>We collect information you provide directly to us, including your name, email address, resume data, and career goals. We also collect usage data to improve our AI models and user experience.</p>
    
    <h2 className="text-xl font-bold text-white mt-8 mb-4">2. How We Use Your Data</h2>
    <p>Your data is primarily used to generate personalized career roadmaps and provide mock interview feedback. We use anonymized data to train and refine our AI algorithms.</p>
    
    <h2 className="text-xl font-bold text-white mt-8 mb-4">3. Data Security</h2>
    <p>We implement industry-standard security measures to protect your data. Resumes are processed securely and stored in encrypted databases.</p>
    
    <h2 className="text-xl font-bold text-white mt-8 mb-4">4. Third-Party Services</h2>
    <p>We use Stripe for payment processing and Google Gemini for AI generation. These services have their own privacy policies which we encourage you to review.</p>
  </StaticPageLayout>
);

export const TermsOfService = () => (
  <StaticPageLayout title="Terms of Service">
    <p>Last Updated: February 21, 2026</p>
    <p>By using Abilities AI, you agree to the following terms and conditions.</p>
    
    <h2 className="text-xl font-bold text-white mt-8 mb-4">1. Use of Service</h2>
    <p>You must be at least 18 years old to use this service. You are responsible for maintaining the security of your account.</p>
    
    <h2 className="text-xl font-bold text-white mt-8 mb-4">2. AI Content Disclaimer</h2>
    <p>The roadmaps and interview feedback generated by our AI are for educational purposes only. We do not guarantee employment or specific career outcomes.</p>
    
    <h2 className="text-xl font-bold text-white mt-8 mb-4">3. Subscription and Payments</h2>
    <p>Premium features require a paid subscription. All payments are processed through Stripe. You can cancel your subscription at any time.</p>
    
    <h2 className="text-xl font-bold text-white mt-8 mb-4">4. Intellectual Property</h2>
    <p>The Abilities AI platform, including its design and proprietary algorithms, is owned by us. You retain ownership of the content you upload (like resumes).</p>
  </StaticPageLayout>
);

export const AboutUs = () => (
  <StaticPageLayout title="About Abilities AI">
    <p className="text-lg text-emerald-400 mb-6">Bridging the gap between ambition and achievement.</p>
    <p>Abilities AI was founded with a simple mission: to make high-level career coaching accessible to everyone. We believe that with the right roadmap and enough practice, anyone can land their dream job.</p>
    
    <h2 className="text-xl font-bold text-white mt-8 mb-4">Our Technology</h2>
    <p>We leverage cutting-edge Large Language Models to analyze your current skills and map out the most efficient path to your target role. Our mock interview engine simulates real-world hiring scenarios to build your confidence.</p>
    
    <h2 className="text-xl font-bold text-white mt-8 mb-4">Our Vision</h2>
    <p>We envision a world where career transitions are seamless and data-driven. No more guessing what skills you need or how to answer tough interview questions.</p>
  </StaticPageLayout>
);

export const Contact = () => (
  <StaticPageLayout title="Contact Us">
    <p className="mb-8">Have questions or feedback? We'd love to hear from you.</p>
    
    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
      <div className="bg-zinc-900 p-6 rounded-2xl border border-white/5">
        <h3 className="text-white font-bold mb-2">Email Support</h3>
        <p className="text-zinc-500 text-sm mb-4">For technical issues or billing questions.</p>
        <a href="mailto:support@abilities.ai" className="text-emerald-400 font-medium">support@abilities.ai</a>
      </div>
      
      <div className="bg-zinc-900 p-6 rounded-2xl border border-white/5">
        <h3 className="text-white font-bold mb-2">Partnerships</h3>
        <p className="text-zinc-500 text-sm mb-4">For business inquiries and collaborations.</p>
        <a href="mailto:hello@abilities.ai" className="text-emerald-400 font-medium">hello@abilities.ai</a>
      </div>
    </div>
    
    <div className="mt-12">
      <h2 className="text-xl font-bold text-white mb-4">Send us a message</h2>
      <form className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <input type="text" placeholder="Name" className="w-full bg-zinc-900 border border-white/10 rounded-lg px-4 py-2 focus:outline-none focus:border-emerald-500" />
          <input type="email" placeholder="Email" className="w-full bg-zinc-900 border border-white/10 rounded-lg px-4 py-2 focus:outline-none focus:border-emerald-500" />
        </div>
        <textarea placeholder="Message" rows={4} className="w-full bg-zinc-900 border border-white/10 rounded-lg px-4 py-2 focus:outline-none focus:border-emerald-500"></textarea>
        <button className="bg-emerald-500 text-black font-bold px-8 py-3 rounded-full hover:bg-emerald-400 transition-colors">
          Send Message
        </button>
      </form>
    </div>
  </StaticPageLayout>
);
